### ISSUE TITLE
Problem with Robolectric

### ISSUE THREAD

**Issue by MitroshinDmitry** [exponea/exponea-android-sdk#12]
When i was try to add Robolectric test to our project, i was encountered with IllegalArgumentException.
Below you can find test project, where that problem was arise.
If you remove dependency from exponea module - the problem will disappear.
When i try to add exponea module manually (by downloading a source code) - problem also not reproduce.
[RobolectricDemo.zip](https://github.com/exponea/exponea-android-sdk/files/2772757/RobolectricDemo.zip)

**Comment by chnt** [comment]
Hi @MitroshinDmitry it looks like your automated tests stops without the system reaching or even referencing the Exponea library.

**Comment by nickskull** [comment]
Since this issue is not caused by the SDK, we're closing it. Let us know if you encounter any issues related to the SDK.

**Comment by a-change** [comment]
Looks like [this solution](https://stackoverflow.com/questions/53987300/robolectric-test-throwing-illegalargumentexception-with-no-message) should help.

**Comment by MitroshinDmitry** [comment]
> Looks like [this solution](https://stackoverflow.com/questions/53987300/robolectric-test-throwing-illegalargumentexception-with-no-message) should help.

 Thanks! It's work for me
