### ISSUE TITLE
Firebase crashes at start up when Exponea and Firebase Performance in same project

### ISSUE THREAD

**Issue by JoshJustPark** [exponea/exponea-android-sdk#14]
Hi,

We are trying to use the Exponea SDK in our app but are running into an issue. using gradle, when I include the Exponea dependency into an app that already has the Firebase Performance dependency. I receive the following fatal error during app start up:

` Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process {app package name}. Make sure to call FirebaseApp.initializeApp(Context) first.`

This error occurs once Ive added the gradle dependency for Exponea. Even if I dont use the sdk or initialise it.

If I remove either Exponea or Firebase performance, the application runs correctly. I believe theres some kind of issue between the two.

These are my following dependency versions:

gradle tools : 3.3.0
kotlin : 1.3.20
firebase plugins: 1.1.5
exponea : 2.0.0
firebase core: 16.0.6
firebase messaging: 17.3.4
firebase performance: 16.2.3

**Comment by Tgo1014** [comment]
@JoshJustPark, can you call `FirebaseApp.initializeApp(Context)` on your `Application()` class and see if it solves the issue?

**Comment by JoshJustPark** [comment]
@Tgo1014 I have tried this as the very first line in the overriden `OnCreate()` method, with no luck

**Comment by Tgo1014** [comment]
@JoshJustPark Just to make sure: do you have a class that extends the `Application()` class and that class is set on your `AndroidManifest.xml`? The reason I'm asking this is that the Firebase "error line link" links to your launcher class, but that isn't were you're supposed to init the Firebase Instance, you **must** init it on the `Application()`.

**Comment by JoshJustPark** [comment]
@Tgo1014 Thanks for the help. We've resolved the issue. The fix was to initialise Firebase from the application class manually. We had a separate conflict which stopped the fix (ie FirebaseApp.InitializeApp) from working the first time.

**Comment by nickskull** [comment]
@JoshJustPark Thanks for the information, glad you could resolve the issue.
