### ISSUE TITLE
Feature request - configuration to set color of push notification icon

### ISSUE THREAD

**Issue by JoshHughes-JP** [exponea/exponea-android-sdk#15]
As a feature request, I would like to be able to set a custom push notification icon color. I think this would probably be easiest as a value in the configuration object, e.g. 

`pushIconColor : Int?`

This could then feed directly into `NotificationCompat.Builder` used in your `FcmManagerImpl` class.

(I understand the same effect can be achieved by using a drawable icon that already has a color, but I think what I'm suggesting is more configurable.)

**Comment by Igi4** [comment]
Hey @JoshHughes-JP , thanks for the idea :) We'll discuss it and I'll let you know as soon as there is any news.

**Comment by wassil** [comment]
Implemented in 2.7.1 https://github.com/exponea/exponea-android-sdk/releases/tag/2.7.1
