### ISSUE TITLE
Crash with WorkManager version 2.1.0

### ISSUE THREAD

**Issue by sviro** [exponea/exponea-android-sdk#17]
When updated work manager in our project to version 2.1.0, this crash occurs:

```
java.lang.NoSuchMethodError: No virtual method setInitialDelay(JLjava/util/concurrent/TimeUnit;)Landroidx/work/OneTimeWorkRequest$Builder; in class Landroidx/work/OneTimeWorkRequest$Builder; or its super classes (declaration of 'androidx.work.OneTimeWorkRequest$Builder' appears in /data/app/com.roadlords.android.debug-2/base.apk)
        at com.exponea.sdk.manager.BackgroundTimerManagerImpl.startTimer(BackgroundTimerManagerImpl.kt:31)
        at com.exponea.sdk.manager.SessionManagerImpl.onSessionEnd(SessionManagerImpl.kt:104)
        at com.exponea.sdk.manager.SessionManager.onActivityPaused(SessionManager.kt:26)
        at android.app.Application.dispatchActivityPaused(Application.java:225)
        at android.app.Activity.onPause(Activity.java:1587)
```

we are using these work manager related libraries:
```
implementation "androidx.work:work-runtime-ktx:2.1.0"
implementation "androidx.work:work-rxjava2:2.1.0"
```

Exponea version we are using is 2.3.1

What's maybe the cause of the problem is that from workmanager version 2.1.0 runtime-ktx requeires Java 8 as is stated here: https://developer.android.com/jetpack/androidx/releases/work#2.1.0

**Comment by levinzonr** [comment]
Hey @sviro 
Managed to reproduce your issue, unfortunaly adding ` kotlinOptions { jvmTarget = "1.8" }`  was not enough.
I have updated `WorkManager` dependency in the SDK to the lastest one, so your problem should disappear :)

I'll make a release with thing patched first thing tomorrow.
Cheers

**Comment by sviro** [comment]
Thanks very much :)

**Comment by levinzonr** [comment]
Morning @sviro 
v2.3.2 is now live, though it might take some time for the artifact to appear in the maven repositories
Let me know how that goes :)

**Comment by sviro** [comment]
It's working like a charm, thanks again.
