### ISSUE TITLE
Lacking documentation about incoming notifications.

### ISSUE THREAD

**Issue by m-o** [exponea/exponea-android-sdk#18]
Hi, we are trying to implement exponea notifications in our android App. But we lack the documentation to do so.
I am able to initialize exponea and even send properties that define user in exponea. I see my user and I see cookie.

What else do i need to do to add firebase to exponea and receive notification?
Should I send the field "google_push_notification_id" also as a property and put firebase token in there?

Are the notifications delivered directly throught firebase or should I implement custom exponea solution from SDK? Thank you

**Comment by Igi4** [comment]
Hey @m-o, you're right with the `google_push_notification_id`, you need to obtain it and track it with the Exponea SDK, e.g.:

```
FirebaseInstanceId.getInstance().instanceId.addOnSuccessListener {
    Exponea.trackPushToken(it.token)
}
```

This is a piece of code we use in the Example app, I copied it from this file: https://github.com/exponea/exponea-android-sdk/blob/develop/app/src/main/java/com/exponea/example/view/fragments/TrackFragment.kt

With this you should be set and can send push notifications with Firebase or Exponea web application.
