### ISSUE TITLE
Push notifications with type "Deep link" do not trigger deeplink action when notification clicked from device lock screen

### ISSUE THREAD

**Issue by JoshHughes-JP** [exponea/exponea-android-sdk#19]
### Issue:

I have set up an Exponea push notification on the web console with type "Deeplink" and a url that should deeplink into my app. 

When testing this whilst a device is unlocked, I successfully receive the push notification and clicking it correctly deeplinks into my app.

When I interact with this push notification on the device lock screen, no deeplink handling is triggered when the the device unlocks.

### Repro steps:

1. The notification is successfully pushed to the device. 
2. Clicking on the notification correctly fires a pending intent broadcast to be handled by the `ExponeaPushReceiver` class. 
3. `ExponeaPushReceiver` receives the intent. _(I can verify this through logging created by the `ExponeaPushReceiver` when it receives a notification)_
4. The Pending intent that should trigger the deeplink action does not fire / work as intented.

**Comment by Igi4** [comment]
@JoshHughes-JP Hey, sorry for the later reply.

Thank you for the repro steps, that'll help.

We'll look into it and I will let you know as soon as I have more information.

**Comment by wassil** [comment]
Hi @JoshHughes-JP,
I'm not able to reproduce this issue, it opens deeplink correctly even from lock screen.
So it seems like it's related to operating system version/device/lock-screen app.
What is the device you're testing on?
Thank you!
