### ISSUE TITLE
Documentation - configuration file name and location

### ISSUE THREAD

**Issue by josepoq** [exponea/exponea-android-sdk#2]
On the CONFIG.md file, you mention that instead of using a configuration class we can use a configuration file, but you do not specify what the name of such class should be nor its location.

**Comment by Tgo1014** [comment]
The documentation has been updated to make it more clear on how to init the SDK with a config file. A example file was added as well. 

You can check the new documentation [here](https://github.com/exponea/exponea-android-sdk/blob/develop/Documentation/CONFIG.md).
