### ISSUE TITLE
Push notification to open app not working

### ISSUE THREAD

**Issue by DmitryKolpo** [exponea/exponea-android-sdk#24]
Installed exponea sdk. Initialized it in my application. I'm able to receive push notifications using exponea web interface.
1. I create a scenario -> create action Mobile Push Notification
```
{
    "title": "Have a nice day!",
    "action": "app"
}
```

2. choose my email in "preview for"
3. click Test push notification
4. click send
5. Tap on the notification.
Expectation: app open
**Reality**: notification disappeared, the app **not opened**

Using other "actions" ("browser" with url or "deeplink" with url) works fine.

Environment:
"device_model":"SM-N950F"
"os_version":"9"
"sdk_version":"2.7.1"
"os_name":"Android"

Unfotinuatly, I can't try another device. I tried to use an emulator, but it ain't receive a push notification (don't know the exact reason, but it's not the point).

**Comment by wassil** [comment]
Hi!
There is a bit more work needed for setting up open app notification action. Please follow https://github.com/exponea/exponea-android-sdk/blob/develop/Documentation/PUSH.md#-responding-to-push-notifications

**Comment by DmitryKolpo** [comment]
Oh, so I **have to** define BroadcastReceiver to be able to handle "open app" notifications, right?

I expected something like in FCM, where some kind of default notifications works out of the box.
And deeplinks works because their handling already has been implemented before in my project.
Ok, thank you for the response.

**Comment by wassil** [comment]
Yeah, the fact you have to define a broadcast receiver sucks. But at the same time you can define which activity you want to open/what to do when you get a notification. We'll consider a better solution, it's reasonable to expect it to "just work"
