### ISSUE TITLE
Leaking sdk dependencies to apps

### ISSUE THREAD

**Issue by ursusursus** [exponea/exponea-android-sdk#26]
Nazdar,
ak vas includujem cez `implementation "com.exponea.sdk:sdk:2.7.2"`, nemal by som vidiet vase tranzitivne kniznice (Gson, PaperDb), ale vidim ich

https://repo1.maven.org/maven2/com/exponea/sdk/sdk/2.7.2/sdk-2.7.2.pom mate tu scope compile, myslim ze to je zdroj problemu

**Comment by wassil** [comment]
Je to presne ako pises. My tiez vsetko includujeme ako `implementation` takze vysledny pom by mal obsahovat scope `runtime` co sa ale nedeje. Vyzera to na problem s publishovanim na maven. Pozriem sa nato, napisem sem ked to bude opravene.

Vdaka za report!

**Comment by wassil** [comment]
Verzia 2.7.3 uz ma spravne nastavene dependecies
