### ISSUE TITLE
Notification sounds not respecting DnD

### ISSUE THREAD

**Issue by ursusursus** [exponea/exponea-android-sdk#28]
Push notifikacie maju zvuk aj napriek tomu ze mam nastavene Do Not Distrurb mod v systeme

To by ste nemali robit. 

Predpokladam ze je to kvoli 
https://github.com/exponea/exponea-android-sdk/blob/e79fb63041980e15ef7a3d335bf5cee26ef37aff/sdk/src/main/java/com/exponea/sdk/manager/FcmManagerImpl.kt#L176

**Comment by wassil** [comment]
To neznie dobre, pozrieme sa nato.
Vdaka za report!

**Comment by wassil** [comment]
Opravene vo verzii 2.8.0
