### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by mistamek** [exponea/exponea-android-sdk#3]
Hi, nice sdk but i faced issue while integrating it into our project. In class **ExponeaFirebaseMessageService** there is crash in line 43
`val data = gson.fromJson(dataString, NotificationData::class.java)`

You trying parse **campaignId** that must be Long, but in push it String. So service crashes with **NumberFormatException**.

**Comment by nickskull** [comment]
This has been fixed, thasks for reporting.
