### ISSUE TITLE
Setting pushIcon in json in Exponea configuration file

### ISSUE THREAD

**Issue by lunicleonid** [exponea/exponea-android-sdk#30]
If @drawable/ic_notification is resolved at runtime how do I set the "pushIcon" in exponea_configuration.json ?

https://github.com/exponea/exponea-android-sdk/blob/master/app/src/main/assets/exponea_configuration.json#L11

**Comment by wassil** [comment]
I'm afraid that's not possible, you'd have to configure the SDK in code https://github.com/exponea/exponea-android-sdk/blob/master/Guides/INSTALL.md#using-code
