### ISSUE TITLE
How to get customer cookie?

### ISSUE THREAD

**Issue by minarja1** [exponea/exponea-android-sdk#31]
Hi and sorry for posting here, I don't know where to address you privately,

we are trying to acquire customer cookie equivalently to iOS-version of this:

`Exponea.shared.customerCookie`

Is this possible with Android SDK?

**Comment by wassil** [comment]
Hi, yup it's `Exponea.customerCookie`

**Comment by minarja1** [comment]
Sorry, I was on version 2.7.2, upgraded and using now :)

**Comment by wassil** [comment]
Ah, that makes sense. I was kind of surprised you didn't find it to be honest ;)
