### ISSUE TITLE
Share OkHttp instance with rest of the app

### ISSUE THREAD

**Issue by ursusursus** [exponea/exponea-android-sdk#34]
```
internal class NetworkHandlerImpl(private var exponeaConfiguration: ExponeaConfiguration) : NetworkHandler {
   private fun setupNetworkClient() {
        val networkInterceptor = getNetworkInterceptor()

        networkClient = OkHttpClient.Builder()
                .addInterceptor(getNetworkLogger())
                .addInterceptor(networkInterceptor)
                .build()
    }
```

90% aplikacii pouziva Okhttp, instanciu by malo byt mozne injectnut cez ExponeaConfiguration, zbytocne duplikujete threadpool vytvaranim vlastnej

**Comment by michaela-dev** [comment]
There are some future plans to add Certificate pinning, so we do not plan to share Okhttp instance with the  app or other libraries, we will probably need to configure our own CertificatePinner.
