### ISSUE TITLE
Notification sound rings twice in some devices

### ISSUE THREAD

**Issue by kannansrepo** [exponea/exponea-android-sdk#35]
I have configured notification sound in the mobile push and added a similar named .wav file in my raw folder of android app. However in certain devices the notification sound is heard twice when a notification comes from exponea. 

Devices: Asus Zenfone Max Pro M2, Samsung Galaxy S8

**Comment by JayanthiVenkatasamy** [comment]
Any updates on above issue ,We are also facing same issue from our users . Currently we use exponea sdk 2.9.3 in our app, the end users hear continuous notification sound from App. They try to stop the notification by restarting the mobile. 
Is this bug already acknowledged?
Impacted device - Sony XQ-AU51
Sony Xperia 1 II
Samsung SM-G996B

**Comment by adam1929** [comment]
Hi @kannansrepo @JayanthiVenkatasamy sorry for late response.
Is this issue still occuring? Please consider a latest SDK 3.1.0 version. This issue didn't happen to our example (I'm not aware of that) but it seems to be device-specific problem :-/

**Comment by JayanthiVenkatasamy** [comment]
Thanks @adam1929  we will update the sdk version and check if the issue is resolved
