### ISSUE TITLE
BroadcastReceiver trampolining forbidden in Android 12

### ISSUE THREAD

**Issue by ursusursus** [exponea/exponea-android-sdk#36]
https://developer.android.com/about/versions/12/behavior-changes-12#notification-trampolines
https://github.com/exponea/exponea-android-sdk/blob/develop/Documentation/PUSH.md#1-open-app

> When users interact with notifications, some apps respond to notification taps by launching an app component that eventually starts the activity that the user finally sees and interacts with. This app component is known as a notification trampoline.
To improve app performance and UX, apps that target Android 12 cannot start activities from services or broadcast receivers that are used as notification trampolines. In other words, after the user taps on a notification, or an action button within the notification, your app cannot call startActivity() inside of a service or broadcast receiver.

Myslim si ze toto je presne tento pripad

**Comment by Igi4** [comment]
Thanks for the report. We'll definitely address this in one of the upcoming releases.

**Comment by ursusursus** [comment]
Bump. Android 12 is about to be stable

**Comment by ursusursus** [comment]
This is a blocker for us

**Comment by michaela-dev** [comment]
Hi, sorry it's taking so long, all changes regarding Android 12 are almost ready and will be part of the major release at the beginning of January. Thanks for your patience 🙏

**Comment by michaela-dev** [comment]
Fixed in version 3.0.0
