### ISSUE TITLE
Improvement - tracking URL with "click" for in-app messages

### ISSUE THREAD

**Issue by MatejBordac** [exponea/exponea-android-sdk#39]
Currently, click responses for in-app messages are tracking only text of button which was clicked.

For example:
Make button in fullscreen in-app with text "Google", which will redirect user to "https://google.com". When in-app is displayed and user clicks on button, event type "banner" is tracked with action = click, attribute text will be set to "Google". So:
action = click
text = Google
_+ other banner attributes..._

Request is to track URL https://google.com as well. So final list of attributes:
action = click
text = Google
url = https://google.com
_+ other banner attributes..._

**Comment by michaela-dev** [comment]
Hi, thanks for your insights! We will consider adding this in one of the next releases.

**Comment by michaela-dev** [comment]
Hi @MatejBordac, this feature was released within 2.9.7 version. Closing the issue.
