### ISSUE TITLE
ExponeaPushReceiver does not receive broadcast on Android O

### ISSUE THREAD

**Issue by josepoq** [exponea/exponea-android-sdk#4]
Android 8.0 changed the receivers that were allowed to be registered on the manifest. With some exceptions, no implicit broadcast receiver is allowed there. The broadcast that ExponeaPushReceiver is expecting is implicit, so it does not work on Android O.

**Comment by josepoq** [comment]
I have created a PR (https://github.com/exponea/exponea-android-sdk/pull/5) that fixes the issue.

**Comment by nickskull** [comment]
Fixed in #5. Thanks for submitting the PR.
