### ISSUE TITLE
Targeting SDK level 31 causing java.lang.IllegalArgumentException: com.myapp.myapp: Targeting S+

### ISSUE THREAD

**Issue by jaroslavhavelik** [exponea/exponea-android-sdk#41]
Exponea is using the old version of  `androidx.work:work-runtime`, which is causing `IllegalArgumentException` app startup, stack trace:

```
java.lang.IllegalArgumentException: com.myapp.myapp: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:386)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:657)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:644)
```

Please update work-runtime to the latest version (currently `2.7.0-alpha05`) to allow targeting Android S.
More details [here](https://stackoverflow.com/questions/67045607/how-to-resolve-missing-pendingintent-mutability-flag-lint-warning-in-android-a)
Possible workaround is to specify `androidx.work:work-runtime:2.7.0-alpha05` to override library version

**Comment by michaela-dev** [comment]
Fixed in version 3.0.0
