### ISSUE TITLE
Gradle failes to download sdk version 2.9.7

### ISSUE THREAD

**Issue by parohy** [exponea/exponea-android-sdk#42]
By looking at [maven repository](https://search.maven.org/search?q=g:com.exponea.sdk) latest version is 2.9.6. We are unable to update to latest sdk version mentioned in the docs.

**Comment by michaela-dev** [comment]
Hi, thanks for the report! It seems like our automatic script to release to maven had some problems, I just released it manually, it should be there in a couple of hours. Sorry for the inconvenience, I will ping you and close the issue once it's actually published.

**Comment by michaela-dev** [comment]
@parohy Version 2.9.7 is published now. Closing the issue
