### ISSUE TITLE
ExponeaFirebaseMessageService is missing android:exported="true"

### ISSUE THREAD

**Issue by PeterBergmann** [exponea/exponea-android-sdk#43]
When targeting api 31 app can't be installed on device with Android 12

https://developer.android.com/about/versions/12/behavior-changes-12#exported

**Comment by dirol90** [comment]
++ same issue, need to be fixed asap

**Comment by PeterBergmann** [comment]
@dirol90 You can add this to manifest as a workaround for now.
```       
 <service
     android:name="com.exponea.sdk.services.ExponeaFirebaseMessageService"
     android:exported="true"/>

**Comment by dirol90** [comment]
> @dirol90 You can add this to manifest as a workaround for now.
> 
> ```
>  <service
>      android:name="com.exponea.sdk.services.ExponeaFirebaseMessageService"
>      android:exported="true"/>
> ```

Yeap, thx, already add it, but rewrite it by hands on each project rebuild is not good practice :) Thx for yours reply, I think it will help other users to find quick solution.

**Comment by michaela-dev** [comment]
SDK versions that support targeting Api 31 ( 3.0.0  and above) no longer contain ExponeaFirebaseMessageService, this service has to be implemented and registered on the App side. android:exported was added at all the places in SDK, where it was needed, and this issue should be solved.
