### ISSUE TITLE
Click on notification with deeplink action does nothing

### ISSUE THREAD

**Issue by LudoFarkas** [exponea/exponea-android-sdk#47]
Hi.

We have updated the Exponea SDK in our app from ver. 2.9.5 to ver. 3.0.3 and the click on received notification with action defined as "deeplink" stopped working.

To be precise, it works only if the app is in foreground. Then the intent is routed to the activity and our app handles the navigation. However, if the same notification is received when the app is in the background or stopped, and the user taps on it, the notification disappears and nothing else happens. The deeplink intent is not even routed to the activity.

The status of the notification in the "Data and Assets" overview is "clicked".

Exponea version: 3.0.3
OS version: Android 11
Device vendor: Xiaomi
Device type: Mi 9

**Comment by LudoFarkas** [comment]
Update:

We have tested this issue with different devices and it apparently occurs on Xiaomi devices (or devices with MIUI). The problem is their "Display pop-up windows while running in the background" permission, which needs to be enabled in order to open the app from Exponea notification. But it is not intuitive for the user to go to the settings and enable it.

However, if we send our own notification with a deeplink, everything is working as expected, irrespective of the setting of the "Display pop-up windows ..." permission.

Could you please look into this.

![IMG_20220328_104843](https://user-images.githubusercontent.com/45174293/160362455-594e0f21-9373-4356-8946-6312dca6c5ab.jpg)

**Comment by michaela-dev** [comment]
Hi, thanks for the update! We are aware that Xiaomi Devices with MIUI OS have various issues with push actions when the app is stopped/killed, but it's new to us this is happening also when the app is in the background.  Can you please send some example of the notification payload you are sending yourself? It would be very helpful 🙏  thanks!

**Comment by LudoFarkas** [comment]
The payload looks like (the URL is redacted):

~~~
{
    "action": "deeplink",
    "actions": [
        {
            "title": "More",
            "action": "deeplink",
            "url": "foo://deeplink/to/the/app"
        }
    ],
    "title": "Deeplink test",
    "message": "Push notification with a deeplink to the app.",
    "url": "foo://deeplink/to/the/app"
}
~~~

**Comment by michaela-dev** [comment]
Hi, I searched a bit and it is caused by MIUI 11+. It does not work well with pending intents which have a back stack configured. It is needed to request permission in order to support notifications with pending intent with configured navigation stack. 

Some sources say, that this permission is granted automatically by google when the app has a target above 30 and is installed from google play, so it will not be granted when installed during development, but I am not able to verify this information. Others just recommend navigating the user to settings if MIUI is present and permission seems not to be granted. 
 Useful references:
 https://stackoverflow.com/questions/59418504/xiaomi-devices-permission-to-enable-apps-pop-up-windows-while-running-in-the-bac https://stackoverflow.com/questions/59214359/anyone-knows-where-is-start-in-background-permission-in-miui-11
https://stackoverflow.com/questions/59051867/permission-to-display-pop-up-windows-while-running-in-the-background

Since Exponea is sending exact same payload, I do not see how this can be handled on our side, and why it (according to your words) works without this permission, when you send the notification by yourself 🤔 are you trying both options on the same environment? 

I will dig some more, but it can take some time.

**Comment by LudoFarkas** [comment]
I have found those SO resources too. But I too cannot confirm that the permission is granted automatically by the Play Store, because the updated app is not live yet.

We have also our own notification sending mechanism except Exponea, that we use for sending other notifications to our app. That is why we have our own notification displaying mechanism which works when navigating to a deeplink when the app is in stopped or in background. Our pending intent creation code looks like:

~~~
private fun createPendingIntent(context: Context, id: Int, deeplink: String?): PendingIntent {
        val intent = Intent(context, MainActivity::class.java).apply {
            if (deeplink != null) data = Uri.parse(deeplink)
        }
        return PendingIntent.getActivity(context, id, intent, createPendingIntentFlagUpdateCurrentCompat())
    }

    private fun createPendingIntentFlagUpdateCurrentCompat(): Int {
        return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT
        } else {
            PendingIntent.FLAG_UPDATE_CURRENT
        }
    }
~~~

I tested it on the exact same build of app as the non-functioning Exponea notification. The older Exponea ver. 2.9.5 worked as expected also without the extra permission.

**Comment by michaela-dev** [comment]
Many thanks for your investigation! We will check pending intent creation in SDK and will try to make some changes to make it work. How pressing is this for you?  We will be able to get to this maybe sometime next week since other work is in progress.

**Comment by LudoFarkas** [comment]
Well, our plan to have the update in the Play Store is in 2 weeks from now, so next week could work I guess.
Thanks for looking into it.

**Comment by michaela-dev** [comment]
Okay, I will make it a priority next week. One more question, does this problem occur only with deep link action sent from the Exponea? Or open app/open web browser actions are also problematic? Or you do not use these?

**Comment by michaela-dev** [comment]
Hi, Thanks for the testing 👍 Unfortunately, I am currently not able to reproduce this issue with multiple Xiaomi devices with MIUI 🤔 on what MIUI version are you facing this issue?

**Comment by LudoFarkas** [comment]
Hi, we have 2 devices with MIUI and the issue is present on both of them:

 1. Xiaomi Mi 9 with MIUI Global 12.5.1 (Android 11)
 2. Redmi Note 8T with MIUI Global 11.0.3 (Android 9)

However, there is one strange thing happening. 
If there are 2 instances of the app installed on a device (2 different packages, but same intent filter to capture deeplinks), the "Open with..." dialog pops up and if I choose one of them, it opens and works. If just 1 app is installed (no "Open with..." dialog), the deeplink is not routed to the app if it is off or in background (as stated in previous comments) 🤷

**Comment by adam1929** [comment]
@LudoFarkas Hi, feel free to summarize your solution here. Other developer may be finding your solution. Thank you.

**Comment by LudoFarkas** [comment]
Hi. If the app is installed from the Play Store, it does not get the permission automatically. So the only solution we found is navigating the users to settings and request them to turn it on, if on a MIUI device.
I am closing this, since there is no action on your side.
