### ISSUE TITLE
README - API/Android support

### ISSUE THREAD

**Issue by taboulot** [exponea/exponea-android-sdk#48]
# Context

The `README` says :
```
This SDK supports API 14+ and Android 4+. If you wish to interact with Exponea on lower API/Android versions please refer to the [old SDK located here](https://github.com/infinario/android-sdk).
```

# Problem  

Since version 3.0.0 and specially this [commit](https://github.com/exponea/exponea-android-sdk/commit/f4efa42053a51043f2be9eda4451e2d538515b6c) `androidx.work:work-runtime-ktx` has been updated to `2.7.1`.

We can see on [this release note](https://developer.android.com/jetpack/androidx/releases/work#version_27_2) that `androidx.work:work-runtime-ktx` > `2.7` needs app to target Android 12 (API 31).

As a consequence, I think the README should  specificy that  Exponea SDK < `3.0.0` support `API 14-30`.

# Question

Am I correct ? 
Should I make a PR for that ?

**Comment by adam1929** [comment]
@taboulot Adding dependency of that kotlin WorkManager library does not creates a requirements for targetSdkVersion. It is opposite of that, so if app is targeting Api 31, it must be using that library :-)
