### ISSUE TITLE
projectToken is empty or missing cause repeating calls to Exponea cloud endpoint  - Android SDK only

### ISSUE THREAD

**Issue by TomasJursa** [exponea/exponea-android-sdk#50]
Dears,
 
 maybe that could be an issue to solve, when accessing Exponea cloud using Exponea Android SDK with empty projectToken.
 The implementation SDK will call multiple times the Exponea api endpoint while the first response code is 404. 
 While the android app using this SDK is widely deployed and used it could cause an situation simillar to DDoS attack.
 My suggestion is to return an application exception while projectToken is empty instead call the endpoint several times.

Thank you,
Tomas

**Comment by adam1929** [comment]
@TomasJursa Thanks for your findings. Yes, we add validations for Android SDK to check a valid project token

**Comment by xcibik00** [comment]
Hi @TomasJursa , added in 3.8.0 Android SDK version
