### ISSUE TITLE
NotificationData subject

### ISSUE THREAD

**Issue by JayanthiVenkatasamy** [exponea/exponea-android-sdk#51]
I have 3.1.0 version , In older version 2.x.x I could able to retrieve the     subject = "my subject" from NotificationData. In recent changes only attributes and campaign data are available. From where we can fetch subject? I have gone through documents from link https://github.com/exponea/exponea-android-sdk/blob/develop/Documentation/PUSH.md but here the NotificationData has subject as param , seems the document is not updated. Can someone help me ?

**Comment by adam1929** [comment]
Hi @JayanthiVenkatasamy 
Thank you for your finding. Yes, documentation is obsolete for that part. Field 'subject' has been removed from NotificationData in v3.0.0
You should be able to find it within 'attributes' now.

**Comment by adam1929** [comment]
@JayanthiVenkatasamy you may use a little help.
Create your mobile push, then activate "code builder". A Json you see now, is what you get as Map<String, String> in your FirebaseMessagingService#onMessageReceived(message) -> message.data
https://documentation.bloomreach.com/engagement/docs/mobile-push-notifications#creating-a-notification-using-the-code-builder
So you are able to find what you want and parse these data in way you want :-)
