### ISSUE TITLE
Manually tracked token is not tracked

### ISSUE THREAD

**Issue by hrach** [exponea/exponea-android-sdk#58]
We are using manual tracking (automaticPushNotification=false).

Until 3.5.0, it was working for us - we are calling `Exponea.trackPushToken` as [described in documentation](https://github.com/exponea/exponea-android-sdk/blob/d31969d2bcec509b4b16831d636e107693f8875e/Documentation/PUSH.md#manual-tracking-of-push-notifications). However, after the update to 3.5.0 it does not work anymore.

We get this warning:
> Push token stored but not tracked: SDK configuration has 'automaticPushNotification' == false

Callstack: 
- [`Exponeta.trackPushToken`](https://github.com/exponea/exponea-android-sdk/blob/d31969d2bcec509b4b16831d636e107693f8875e/sdk/src/main/java/com/exponea/sdk/Exponea.kt#L470)
- [`trackPushTokenInternal` withe `TokenFrequency.EVERY_LAUNCH`](https://github.com/exponea/exponea-android-sdk/blob/d31969d2bcec509b4b16831d636e107693f8875e/sdk/src/main/java/com/exponea/sdk/Exponea.kt#L489)
- [`FCMManagerImpl.trackToken` with `TokenFrequency.EVERY_LAUNCH`](https://github.com/exponea/exponea-android-sdk/blob/d31969d2bcec509b4b16831d636e107693f8875e/sdk/src/main/java/com/exponea/sdk/manager/FcmManagerImpl.kt#L72) - the `shouldUpdateToken` is always `true`, we get the warning, and web interface shows empty `google_push_notification_id`.

**Comment by hrach** [comment]
cc @adam1929

**Comment by adam1929** [comment]
Hi @hrach thank you for your finding.
Push token is not send into BE when you have automaticPushNotification=false -> confirmed.
We'll bring fix, thank you

**Comment by xcibik00** [comment]
Hi @hrach, sorry for the delay, we know about that, currently backlog item -> we will let you know when the fix will be released, hopefully next Android release will contain it.
Thanks for your patience

**Comment by xcibik00** [comment]
Hi @hrach , fixed in 3.8.0 Android SDK version
