### ISSUE TITLE
Lock contention issue

### ISSUE THREAD

**Issue by egeorgetNiji** [exponea/exponea-android-sdk#61]
Lock contention

The main thread was blocked trying to acquire a lock that was held by another thread.

Current sdk version: 3.7.0

<img width="1209" alt="image" src="https://github.com/exponea/exponea-android-sdk/assets/88028693/5a8c5302-c4b8-4712-b691-c34c5bf739b1">
<img width="804" alt="Capture d’écran 2023-10-13 à 11 02 30" src="https://github.com/exponea/exponea-android-sdk/assets/88028693/9dadba4d-26e2-48bf-af6b-782c6ed059bf">

**Comment by adam1929** [comment]
Thank you @egeorgetNiji for your finding. Truly, 'data processing' should be done asynchrously, not in Main thread. We check that.

**Comment by xcibik00** [comment]
Hi @egeorgetNiji , fixed in Android SDK 3.8.0
