### ISSUE TITLE
Shutting down the Cloud Messaging API (Legacy) in June, 2024

### ISSUE THREAD

**Issue by sergei-mikhailovskii-idf** [exponea/exponea-android-sdk#62]
Hi! I think you already know, that in June, 2024 Google shuts down the legacy HTTP or XMPP APIs and users must migrate to the latest Firebase Cloud Messaging API (HTTP v1). Now our app uses legacy Server Key instead of the new Private Key. Is there any way to migrate to the new approach now or are there any estimates where we would have an opportunity to do it? Thanks in advance for the answer!

**Comment by xcibik00** [comment]
Hi @sergei-mikhailovskii-idf , we will work on it during Q1 2024.
For more info please reach the official Engagement Support [via these recommended ways](https://documentation.bloomreach.com/engagement/docs/engagement-support#contacting-the-support)
