### ISSUE TITLE
Campaign parameter xnpe_cmp should not be required

### ISSUE THREAD

**Issue by gahms** [exponea/exponea-android-sdk#63]
When we try to track a campaign from a launch URL, we meet the odd requirement from the Android SDK that the parameter `xnpe_cmp` is required for the SDK to consider the campaign data to be valid. 

This is when we call `Exponea.handleCampaignIntent()` which later call `CampaignData.isValid()`. The function `isValid()` considers the parameter `xnpe_cmp` and _only_ this parameter when it evaluates the campaign data.

The iOS SDK does not require `xnpe_cmp` to be included in the URL.

**Comment by adam1929** [comment]
Hi @gahms thank you for finding. Attribute `xnpe_cmp` does not need additional validation; validation will be removed.

**Comment by gahms** [comment]
@apunn-branch I have not checked. It should be pretty easy to find the function I mention and check in the source code.

**Comment by adam1929** [comment]
Hi @apunn-branch field `xnpe_cmp` is not required for both iOS and Android SDKs. All mentioned fields are not required but used for tracking if are available while processing URL.

**Comment by apunn-branch** [comment]
@gahms @adam1929 thank you so much for your response! Are those fields automatically appended onto the URL by Exponea when the email is sent? or is that the user's responsibility to manually add them? If the latter, what would the values be for those fields?

**Comment by xcibik00** [comment]
Hi @apunn-branch 

If those links are marked as ULs, this param is added automatically as described https://documentation.bloomreach.com/engagement/docs/universal-link#tracked-event, but we are mobile SDK tech team - so in case of issue/question regarding Engagement, please contact official support https://documentation.bloomreach.com/engagement/docs/engagement-support#contacting-the-support.

Thanks!

**Comment by apunn-branch** [comment]
@xcibik00 thank you so much for your assistance, I really appreciate it!
