### ISSUE TITLE
Image Decoding on Main Thread

### ISSUE THREAD

**Issue by sergei-mikhailovskii-idf** [exponea/exponea-android-sdk#65]
Hello! We use exponea-android-sdk and during the profiling found the issue that can lead to ANRs - Image Decoding on Main Thread (https://github.com/exponea/exponea-android-sdk/blob/bf48aba5a58e5632bdc5d963c18ee24d7e200ec9/sdk/src/main/java/com/exponea/sdk/view/InAppMessagePresenter.kt#L122). We measured the duration of the decoding with Sentry and sometimes it takes up to 930ms. Is it possible to move the decoding to the background thread? Thanks in advance for the answer, feel free to ask me for any support u need!

**Comment by adam1929** [comment]
Hi @sergei-mikhailovskii-idf thank you for reporting. We need to check if asynchronous decode-ing is possible.
This image decoding is done locally so duration 930ms seems for case of HUGE image :-O.
We have no recommendation for that, what is size of your image? Can you please consider to use smaller one?
Thank you

**Comment by sergei-mikhailovskii-idf** [comment]
Hi @adam1929. let me check with the team which images are using for sending and I'll be back with the answer. thanks!

**Comment by sergei-mikhailovskii-idf** [comment]
Hi @adam1929. found out that the image dimensions are 1080x1920 and the size is about 1.5 MB. yes, we'll try to use smaller images but the background decoding also seems to be one of the ways to improve the SDK also :) anyway, thanks a lot for the help!

**Comment by adam1929** [comment]
Hi @sergei-mikhailovskii-idf thank you for such an info.
I also think that 1,5MB or fullhd image should NOT be problem for local decompressing. Duration of 1s is quite a lot :-/
We'll think how to put into background thread.
Thank you
