### ISSUE TITLE
Conflict between Exponea SDK WorkManager Initialization and WorkManager initialization in Application.

### ISSUE THREAD

**Issue by valentynsmetanin** [exponea/exponea-android-sdk#67]
## Conflict between Exponea SDK WorkManager Initialization and WorkManager initialization in Application class.

I'm using WorkManager in conjunction with [HiltWorkerFactory](https://developer.android.com/training/dependency-injection/hilt-jetpack#workmanager) to inject dependencies needed to our Workers. I'm facing with issue that our Worker creations fails with next Exception:
```
Could not instantiate ua.com.app.debug.DownloadWarrantyWorker java.lang.NoSuchMethodException: ua.com.app.debug.worker.DownloadWarrantyWorker.<init> [class android.content.Context, class androidx.work.WorkerParameters]
at java.lang.Class.getConstructor0(Class.java:2363)
at java.lang.Class.getDeclaredConstructor(Class.java:2201)
at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:94)
at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:243)
at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:144)
at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at java.lang.Thread.run(Thread.java:1012)
ua.com.app.debug   Could not create Worker ua.com.app.debug.DownloadWarrantyWorker
```
If I remove initialization of Exponea SDK `Exponea.init(context, configuration)` Workers creates properly.

According to latest [WorkManager configuration](https://developer.android.com/develop/background-work/background-tasks/persistent/configuration/custom-configuration) with [Hilt](https://developer.android.com/training/dependency-injection/hilt-jetpack#workmanager)
I configured our WorkManager as:
Application
```
@HiltAndroidApp
class App : MultiDexApplication(), Configuration.Provider {
    
    @Inject
    protected lateinit var workerFactory: HiltWorkerFactory

    override val workManagerConfiguration: Configuration
        get() = Configuration.Builder()
            .setWorkerFactory(workerFactory)
            .build()

    override fun onCreate() {
        super.onCreate()

        val configuration = ExponeaConfiguration().apply {
            projectToken = "token"
            authorization = "auth"
            baseURL = "base url"
            httpLoggingLevel = ExponeaConfiguration.HttpLoggingLevel.NONE
            automaticPushNotification = true
        }
        Exponea.init(this, configuration)
    }
}
```
InitializationProvider for custom initialization in AndroidManifest:
```
<provider
       android:name="androidx.startup.InitializationProvider"
       android:authorities="${applicationId}.androidx-startup"
       android:exported="false"
       tools:node="merge">
            <meta-data
                android:name="androidx.work.WorkManagerInitializer"
                android:value="androidx.startup"
                tools:node="remove" />
</provider>
```
Example of worker
```
@HiltWorker
class DownloadDocumentWorker @AssistedInject constructor(
    @Assisted appContext: Context,
    @Assisted params: WorkerParameters,
    private val repository: Repository,
) : CoroutineWorker(appContext, params)
```

### Obviously Exponea SDK needed WorkManager either.
Seems like `Exponea.init(context, configuration)` method calls `WorkManager.initialize(context, Configuration.Builder().build())`under the hood, that overrides declared configuration in our Application class.

```
object Exponea {
    @Synchronized
    fun init(context: Context, configuration: ExponeaConfiguration) = runCatching {
        //...
        initializeSdk(context)
        //...
    }

    private fun initializeSdk(context: Context) {
        // ...
        initWorkManager(context)
        // ...
    }

    private fun initWorkManager(context: Context) {
        try {
            WorkManager.initialize(context, Configuration.Builder().build())
        } catch (e: Exception) {
            Logger.i(this, "WorkManager already init, skipping")
        }
    }
}

### Workaround
```
As you could know when you calls `WorkManager.initialize(context, Configuration.Builder().build())` it creates singleton instance of WorkManager with default configuration which does have DefaultWorkerFactory. This is why our instance of WorkManager doesn't know about declared HiltWorkerFactory in our Application class.
As a workaround we can direct re-init WorkManger calling `WorkManager.initialize(this, workManagerConfiguration)` in our Application class which is works.
```
@HiltAndroidApp
class App : MultiDexApplication(), Configuration.Provider {

    @Inject
    protected lateinit var workerFactory: HiltWorkerFactory

    override val workManagerConfiguration: Configuration
        get() = Configuration.Builder()
            .setWorkerFactory(workerFactory)
            .build()

    override fun onCreate() {
        super.onCreate()

        val configuration = ExponeaConfiguration().apply {
            projectToken = "token"
            authorization = "auth"
            baseURL = "base url"
            httpLoggingLevel = ExponeaConfiguration.HttpLoggingLevel.NONE
            automaticPushNotification = true
        }
        Exponea.init(this, configuration)
        
        WorkManager.initialize(this, workManagerConfiguration)
    }
}
```
But this workaround has several not obvious at first glance issues:
1. `WorkManager.initialize` is recommended way for [Custom initialization before WorkManager 2.1.0](https://developer.android.com/develop/background-work/background-tasks/persistent/configuration/custom-configuration#pre-2.1.0), latest WorkManager version is 2.9.0.
2. Our Application class calls `WorkManager.initialize` two times in a row that **leads to ANR**.

### Possible Solution
As a solution could you avoid using `WorkManager.initialize` or change your `private fun initWorkManager(context: Context)` to use `workManagerConfiguration` from application class if it implements `Configuration.Provider`:
```
private fun initWorkManager(context: Context) {
        try {
            val configuration = if (context is Configuration.Provider) {
                context.workManagerConfiguration
            } else {
                Configuration.Builder().build()
            }
            WorkManager.initialize(context, configuration)
        } catch (e: Exception) {
            Logger.i(this, "WorkManager already init, skipping")
        }
    }
```

### Environment
```
implementation "com.exponea.sdk:sdk:3.11.2"

implementation 'androidx.work:work-runtime-ktx:2.9.0'

implementation "androidx.hilt:hilt-work:1.0.0"
kapt "androidx.hilt:hilt-compiler1.0.0"

implementation "com.google.dagger:hilt-android:2.50"
kapt "com.google.dagger:hilt-android-compiler:2.50"
```

The issue arises from the Exponea SDK's attempt to initialize WorkManager with a default configuration, overriding custom configurations set in the Application class. As a result, Worker creation fails.

I believe that addressing this conflict within the Exponea SDK's initialization process would help resolve the issue without the need for workarounds or modifications on the client side.

I appreciate your attention to this matter and look forward to your insights and solutions. If you require any additional information or details regarding my setup or the issue at hand, please don't hesitate to reach out.

**Comment by adam1929** [comment]
Hi @valentynsmetanin what a nice analysis, thank you!
Unfortunately and you also understands that these library-compatibility issues are occurring time-to-time.
I need to say that we should not to use WorkManager from application context because we are not aware how it is configured and our SDK internal processes are relating on WorkManager setup.
In short, there could be chance that developer may configure WM with non-compatible setup, SDK will use it and scheduled processes (session tracking) could fail. And such a "issue" is hard to find.
Anyway, really thanks to such a deep detailed analysis, this helps to us look at it if could be used in SDK and it really can help  other developers to handle such an issue.

**Comment by valentynsmetanin** [comment]
@adam1929, thanks a lot for getting back to me so quickly!
Would you mind analyze another solution? You can skip call `WorkManager.initialize(context, configuration)` at all. Simple call `WorkManager.getInstance(context)` uses `WorkManager.initialize` under the hood with configuration which can be managed by client app without affecting SDK behaviour.

```
public static @NonNull WorkManager getInstance(@NonNull Context context) {
        return WorkManagerImpl.getInstance(context);
}

public static @NonNull WorkManagerImpl getInstance(@NonNull Context context) {
        synchronized (sLock) {
            WorkManagerImpl instance = getInstance();
            if (instance == null) {
                Context appContext = context.getApplicationContext();
                if (appContext instanceof Configuration.Provider) {
                    initialize(
                            appContext,
                            ((Configuration.Provider) appContext).getWorkManagerConfiguration());
                    instance = getInstance(appContext);
                } else {
                    throw new IllegalStateException("WorkManager is not initialized properly.  You "
                            + "have explicitly disabled WorkManagerInitializer in your manifest, "
                            + "have not manually called WorkManager#initialize at this point, and "
                            + "your Application does not implement Configuration.Provider.");
                }
            }

            return instance;
        }
    }
```
It doesn't affect SDK behaviour and keeps flexibility of using custom Configuration.
I'm looking forward for you reply.

**Comment by valentynsmetanin** [comment]
Hi @adam1929  👋 Just curious — I noticed that the issue I previously reported seems to be gone (I'm using v4.5.0). Were there any changes related to that, or was it resolved incidentally? Either way, thanks! 😊

**Comment by adam1929** [comment]
Hi @valentynsmetanin there was no direct change in SDK for WorkManager. I assume that your app upgrades WorkManager to newer version and "fixation" or handling of multiple initialisation has changed there. Good to know, thank you for update!
