### ISSUE TITLE
Notification sound is played while the Notification chanel is set to be silent

### ISSUE THREAD

**Issue by dimakpoq** [exponea/exponea-android-sdk#69]
Hello, we have complaints from the users, that the sound still plays on the Silent push notification channels. We can reproduce this issue on Android Oreo and up.

Exponea: 3.13.0

Actual result:
- In the device Settings search for Notifications category.
- Select application from the list of apps.
- Click on the Exponea Notification channel name.
- Select the 'Silent' level for this channel.
- Close Settings.
- Send test push notification.
- When notification arrives sound is played.

Expected result:
- When notification arrives for silent channel, then sound is _not_ played.

When the channel is set to be silent, the priority of such channel is set by OS to IMPORTANCE_LOW or IMPORTANCE_MIN, as stated in Android docs here: 
[Notication channel importance levels](https://developer.android.com/develop/ui/views/notifications/channels#importance) 

However, as far as we can see in Exponea the channel is tested only for condition IMPORTANCE_NONE when considering sound playback. Could it be fixed to include IMPORTANCE_LOW, IMPORTANCE_MIN in the check?

**Comment by adam1929** [comment]
Thank you @dimakpoq  for reporting this behaviour. We'll check for other channel importance levels to play notification sound.

**Comment by dimakpoq** [comment]
Hello, 
Is it possible by any chance to know the estimated time of arrival for this fix? 

Thank you.

**Comment by xcibik00** [comment]
Hi @dimakpoq , its already a part of 3.16.0 version
