### ISSUE TITLE
Migrate from javax.annotation:jsr250-api:1.0

### ISSUE THREAD

**Issue by Vlado24** [exponea/exponea-android-sdk#74]
The current version of `org.danilopianini:gson-extras (v0.2.2) `used in the project includes a dependency on `javax.annotation:jsr250-api:1.0`. This library version is outdated and it's lead to compatibility issues, which we are facing right now.

Reference to a Similar Issue Resolved by Another Library:
Dagger, a widely used dependency injection library, had a similar issue and resolved it as documented here: [Dagger Issue #3480](https://github.com/google/dagger/issues/3480). This change involved migrating away from the deprecated annotations to newer ones, which has proven to be effective and beneficial for maintaining compatibility.

Action Requested

Could the maintainers of this project consider updating the gson-extras dependency from 0.2.2 to 1.3.x? This update would eliminate the use of the outdated `javax.annotation:jsr250-api:1.0` and align with best practices for library maintenance.

Thank you.

**Comment by ursusursus** [comment]
I've run into the same issue
