### ISSUE TITLE
InAppMessageCallback: inAppMessageAction interaction value is wrong

### ISSUE THREAD

**Issue by janhofman** [exponea/exponea-android-sdk#77]
There's a incorrect behavior of 
```
interface InAppMessageCallback
fun inAppMessageAction(message: InAppMessage, button: InAppMessageButton?, interaction: Boolean, context: Context)
```

When receiving callback after clicking on button within InAppMessage `interaction` equals `false` if the button is setup with type `Cancel`.
<img width="169" alt="Screenshot 2024-09-20 at 12 09 47" src="https://github.com/user-attachments/assets/5d8d08ad-d62e-4439-8a4b-d4cc77c82dca">

I've compared this with iOS sdk and it behaves as expected. `intaraction` is `true` when clicking on the button

**Comment by adam1929** [comment]
Thank you @janhofman for reporting. Please which In-app message type you used? HTML, modal, etc.
Thank you

**Comment by janhofman** [comment]
Modal, configuration looks like this:
![Screenshot 2024-09-24 at 11 39 05](https://github.com/user-attachments/assets/bf511e4b-2da1-4640-b14f-3881f7642987)
![Screenshot 2024-09-24 at 11 36 47](https://github.com/user-attachments/assets/73a8a593-1c9c-4b88-96e2-d94124f59c59)

**Comment by adam1929** [comment]
Hi @janhofman please try to integrate new Android SDK 4.0.0, it also contains new InApp callback interface, more precise for your usage.
I tried modal In-app with Cancel button and seems tracked fine - interaction true, action close, and (new feature) text with text of cancel button.
Please feel free to reopen issue if still occurring in your setup and usage. Thank you
