### ISSUE TITLE
Cannot upgrade gradle (AGP) because namespace in module's build.gradle isn't specified

### ISSUE THREAD

**Issue by VeesileNavi** [exponea/exponea-android-sdk#78]
A problem occurred configuring project ':exponea'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

Please, add namespace = "com.example" to android section in your build.gradle file. It is necessary since gradle 8.x.x.

**Comment by VeesileNavi** [comment]
sorry,  wrong repo. will be reopened in flutter_sdk

**Comment by xcibik00** [comment]
Hi @VeesileNavi I think its already addressed with https://github.com/exponea/exponea-flutter-sdk/pull/28
