### ISSUE TITLE
When Exponea server returns 502, the app can crash

### ISSUE THREAD

**Issue by nabucho** [exponea/exponea-android-sdk#8]
When we do have issues with Exponea tracking on server, the app can crash in okHttp.

it probably should be handled in our interceptor - https://github.com/square/okhttp/issues/3301 

[com.allgoritm.youla_issue_35901_crash_5BFBCADC00DF000142395FE8CF0BE3CC_DNE_0_v2.txt](https://github.com/exponea/exponea-android-sdk/files/2619866/com.allgoritm.youla_issue_35901_crash_5BFBCADC00DF000142395FE8CF0BE3CC_DNE_0_v2.txt)

**Comment by Tgo1014** [comment]
A possible fix for this issue is being deployed in the version `1.2.0-beta-4`.
